#!/bin/bash

THEME_DIR="$HOME/.config/waybar/themes"
WAYBAR_STYLE="$HOME/.config/waybar/style.css"

choice=$(ls "$THEME_DIR" | wofi --dmenu --prompt "Escolher tema")

if [ -n "$choice" ]; then
    cp "$THEME_DIR/$choice" "$WAYBAR_STYLE"
    pkill waybar
    sleep 0.5
    nohup waybar >/dev/null 2>&1 &
fi